### ISSUE TITLE
trouble sending osc over LAN

### ISSUE THREAD

**Issue by jaschanarveson** [colinbdclark/osc.js#83] opened 2017-03-17 12:38 UTC
Apologies for what is doubtless a user question and not a bug report, but: I'm having trouble sending OSC over a LAN, and I can't figure out why.

Attached are a simple send program and a receive program.  When I run the attached send and receive code on a single machine, it works fine.

When I set up two laptops ("oldwhoohoo" and "jascha") with the attached code, I get the following error on the laptop that's sending:

```
oldwhoohoo:TenthIntervention_MuseVisualizer-master changeme$ node zzz-lansend.js 
ready
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: send EADDRNOTAVAIL jascha.local:9999
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:345:11)
```

I've tried sending over my regular apartment router LAN and also via the "Create Network" option on my (Apple) laptops.  In each case, I can ping from one machine to the other no problem.

For reference, here are the programs I'm running.

**Receiving on "jascha.local"**
```
var osc = require("osc");
var udp = new osc.UDPPort({
    localAddress: "jascha.local",
    localPort: 9999
});

udp.open();

udp.on("ready", function () {
    console.log("receiver is ready");
});

udp.on("message", function(message, timetag, info) {
   console.log(message); 
});
```

**Sending from "oldwhoohoo.local" to "jascha.local"**
```
var osc = require("osc");

var udp = new osc.UDPPort({
    localAddress: "127.0.0.1", 
    localPort: 5000, 
    remoteAddress: "jascha.local",
    remotePort: 9999
});

udp.open();

udp.on("ready", function () {

    console.log("ready");
    setInterval(function () {
        udp.send({
            address: "/sending/every/second",
            args: [1, 2, 3]
        })
    }, 1000);
});
```

**Comment by colinbdclark** [comment] 2017-03-18 15:31
Hi @jaschanarveson! Off the top of my head, I'm not sure what the issue is. I guess the first thing to double check is that ports 9999 and 5000 are available on your respective laptops. Secondly, I might try using the computer's IP address directly rather than the mDNS hostname, just in case there's an issue with resolving them for some reason.

Let me know how it goes,

Colin

**Comment by jaschanarveson** [comment] 2017-03-18 15:58
Hi, Colin -

Alas!  Doesn't work.  Here's what I did:

- double-checked that my firewall was off on both laptops (it was)
- used ping to ascertain the IP address of jascha.local and then plugged the proper IPv4 address into the sender code
- ran it - same error as above, but with "192.168.0.5" instead of "jascha.local"
- tried it again with a different port number: 57120 - didn't work
- sending from the "oldwhoohoo" laptop to "jascha.local" using SuperCollider works just fine, so it isn't my router blocking OSC traffic or anything.

Any other thoughts?

**Comment by jaschanarveson** [comment] 2017-03-24 13:30
Hey, Colin -

Any further thoughts?  I'm still stuck with the setup I'm using...  I find it interesting and weird that SuperCollider can send OSC to jascha.local:57120 when Node+osc.js can't...

cheers,

j

**Comment by jean-emmanuel** [comment] 2017-03-24 16:30
Which version of node are you using ?

**Comment by jaschanarveson** [comment] 2017-03-24 17:34
I'm using the latest osc.js and Node 4.0.5.

**Comment by jean-emmanuel** [comment] 2017-03-25 09:51
I can't reproduce the bug here. Does supercollider uses the udp protocol for sending osc too ?

**Comment by jaschanarveson** [comment] 2017-03-25 11:56
Hi, Jean-Emmanuel -

Yeah, SuperCollider mainly uses UDP.  

Were you running the same code I attached above (with the obvious differences in machine names)?  

Are you using Node 4.5.0, too?

**Comment by jaschanarveson** [comment] 2017-03-25 13:06
Ok!  I finally got it working - it turns out I couldn't use "127.0.0.1" or "localhost" for the localAddress if I was going to be sending over a LAN - I needed to have the LAN address of the sending machine listed as localAddress, instead.

So, with the machine "oldwhoohoo.local" sending to "jascha.local" the options would be:

```
{
    localAddress: "oldwhoohoo.local",
    localPort: 5000,
    remoteAddress: "jascha.local",
    remotePort: 8888
}
```
...and then jascha.local would obviously need to be:
```
{
    localAddress: "jascha.local",
    localPort: 8888
}
```

Maybe I'll add this example to the osc.js-examples repo...

cheers,

j

**Comment by jean-emmanuel** [comment] 2017-03-25 16:57
Hmm, does it work with `0.0.0.0` too ?

**Comment by jaschanarveson** [comment] 2017-03-25 18:00
Oh!  Totally works with 0.0.0.0.  I just Googled and read up on the difference between 127.0.0.1 and 0.0.0.0 and I see what's happening, now.

Thanks!

**Comment by colinbdclark** [comment] 2017-03-30 22:49
@jaschanarveson I'm glad to hear you ended up getting it to work, and I'm sorry for the trouble you encountered.

As you discovered, you do indeed to make sure your sending UDPPort is also bound to an appropriate network interface; <code>127.0.0.1</code> is the loopback interface, so it will only allow you to connect to your own local computer. Sorry I didn't notice this sooner.

osc.js does different from a raw Node.js UDP socket in this respect, as documented in #52. With a plain Node.js socket, if you omit the local address, it will bind to <code>0.0.0.0</code>, which is the "all interfaces" address--meaning it will bind to all of your computer's network interfaces. However, osc.js will always default to <code>127.0.0.1</code> if you don't specify a <code>localAddress</code> option when you instantiate a <code>osc.UDPPort</code> object. I'm not sure this is the least confusing or correct behaviour, and it may be addressed in a future major release of osc.js--but I don't want to change the API in backwards-incompatible ways until I have a significantly motivating batch of changes to make at once.

In your case, you were explicitly setting <code>localAddress</code> to <code>127.0.0.1</code>, but omitting it altogether would have had the same effect. To connect to a remote computer, you have to bind to a network interface. If your IP address is changing a lot, like if you're working something at home and then want to bring it to a gig, using <code>0.0.0.0</code> is probably the easiest solution.

This definitely needs to be added to the osc.js documentation so that others don't stumble on the same problem you did. I'll file a separate ticket for updating the documentation to explain this.

Thanks @jean-emmanuel for your help triaging this issue, and thanks for reporting it @jaschanarveson.

**Comment by jaschanarveson** [comment] 2017-03-30 23:08
Yeah - it all makes sense now that I understand what's happening!  

It's funny: during years of sending OSC over SuperCollider, I never had to explicitly set the address of the sending machine, which means SC must have been finding the proper network interface on its own while I wasn't looking.  The loopback thing makes total sense - I just never had to think about it before now...

Thank you both!

Colin: I'll leave the closing of the issue to you, if you want to leave it open as a reminder to update the documentation...

cheers,

j

**Comment by colinbdclark** [comment] 2017-03-30 23:18
Thanks @jaschanarveson! I bet SuperCollider is also defaulting to <code>0.0.0.0</code>, but I haven't looked at the source code. I have filed #87 to cover the documentation issue. Good luck with you project; I'm always interested in hearing about cool things people are using my libraries for, so keep me posted!

**Closed by colinbdclark** 2017-03-30 23:18 UTC
